apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.sigs.dev
spec:
  group: scheduling.sigs.dev
  names:
    kind: Queue
    plural: queues
    shortNames:
      - q
      - queue-v1alpha2
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight:
              format: int32
              type: integer
            capability:
              type: object
            state:
              type: string
          type: object
        status:
          properties:
            state:
              type: string
            unknown:
              format: int32
              type: integer
            pending:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
            inqueue:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha2
  subresources:
    status: {}
